[project]
name = "nhp-functional-area-mapping"
version = "0.1.0"
description = "Code for mapping results from NHP demand model runs to functional areas, for conversion to capacity"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-data-tables>=12.7.0",
    "azure-identity>=1.25.1",
    "azure-storage-blob>=12.28.0",
    "databricks-connect>=18.0.3",
    "dotenv>=0.9.9",
    "nhp-products@git+https://github.com/the-strategy-unit/nhp_products.git@v5.1.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pyspark>=3.5.6",
]

[build-system]
requires = ["setuptools>=80", "setuptools-scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
nhp-products = { git = "https://github.com/The-Strategy-Unit/nhp_products", rev = "v5.1.0" }
